apiVersion: v1
kind: Service
metadata: 
  name: db
  labels: 
    name: postgres-service
    app: voting-app
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres-app-pod
    app: voting-app
