apiVersion: v1
kind: Service
metadata: 
  name: result-service
  labels:
    name: result-service
    app:
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 31221
  selector:
    name: result-app-pod
    app: voting-app


